### ISSUE TITLE
Grasping Issue

### ISSUE THREAD

**Issue by Muhammad441** [caelan/pybullet-planning#7]
Hi,

I am trying to grasp small blocks in pybullet using the PR2 gripper. However, I notice that there are some artifacts that I encounter while actually grasping the objects. This leads to significant inconsistencies. I have attached a gif of one such artifact. Can someone confirm the source of this issue and possible solutions?

In the example below, the gripper is closed by position controlling to a pre-determined value. There are also cases, where the gripper does not properly grasp the object causing it to fall. 

The PR2 model was taken from this repository.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/11947519/104827812-e3978f80-582f-11eb-964c-7c443f23df80.gif)

**Comment by caelan** [comment]
This repository doesn't add any significant simulation functionality over https://github.com/bulletphysics/bullet3, so the issue/difficulty isn't within the scope of this repository. Realistically simulating grasping can be challenging. PyBullet's [documentation](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#) and forums have some recommendations for improving reliability by, for example, changing the frictional properties of the block and gripper.

**Comment by Muhammad441** [comment]
Sure, yes. I just wanted to verify the issue did not lie with the PR2 model. And confirm if the grasping functionality has been successfully implemented in this repository. 

As per my perusal, I see that the objects are being attached to the arm/hand directly rather than actually simulating the grasp. If I am wrong could you please point me to the relevant files/functions. Thank you!

**Comment by caelan** [comment]
I typically doesn't use PyBullet's physics simulation capability during planning. Instead, I use attachments to maintain the current kinematic tree for visualization and collision-checking purposes. Again, simulating stable grasps is difficult, so I avoid it unless I'm treating the simulator as ground truth (rather than the real world). If you want to use the physics simulator without worrying about grasping, you can add [constraints](https://github.com/caelan/pybullet-planning/blob/master/pybullet_tools/utils.py#L3429) to further stabilize the grasping process.
